version: 2
updates: 
  # Enable version updates for nuget 
  — package-ecosystem: “nuget”
  # Look for NuGet dependency info from the `root` directory
  directory: “/” 
  # Check the nuget registry for updates every day (weekdays) schedule: 
  interval: “daily"
