version: '3.4'

services:
  api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=https://+:7100;http://+:7010
      - ASPNETCORE_HTTPS_PORT=7100
      - ASPNETCORE_Kestrel__Certificates__Default__Password=password!
      - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/cert.pfx
      - DbConfig__UseInMemoryDb=false
      - DbConfig__Provider=postgresql
      - DbConfig__ConnectionString=Server=postgres;Port=5433;Database=fshdb;User Id=posgresqladmin;Password=posgresqladmin
      - Serilog__WriteTo__2__Args__serverUrl=http://seq:5341
    ports:
      - 7010:7010
      - 7100:7100
    volumes:
      - ~/.aspnet/https:/https:ro