version: '3.4'

services:
  dotnet-webapi:
    image: "iammukeshm/dotnet-webapi"
    environment:
      - "MultitenancySettings__ConnectionString=Host=db;Database=rootTenantDb;U\
        sername=postgres;Password=root;Include Error Detail=true"
      - "MultitenancySettings__DBProvider=postgresql"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_URLS=https://+:5053;http://+:5063"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5053:5053"
      - "5063:5063"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    container_name: dotnet-webapi-with-postgresql
  db:
    image: "postgres:latest"
    environment:
      - "POSTGRES_PASSWORD=root"
    container_name: postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
