version: '3.4'
services:
  dotnetwebapi:
    image: "iammukeshm/dotnet-webapi"
    environment:
      - "MultitenancySettings__ConnectionString=server=db;uid=root;pwd=root;dat\
        abase=rootTenantDb;Allow User Variables=True"
      - "MultitenancySettings__DBProvider=mysql"
      - "ASPNETCORE_Kestrel__Certificates__Default__Password=securePassword123"
      - "ASPNETCORE_Kestrel__Certificates__Default__Path=/https/aspnetapp.pfx"
      - "ASPNETCORE_URLS=https://+:5052;http://+:5062"
    volumes:
      - ~/.aspnet/https:/https:ro
    ports:
      - "5052:5052"
      - "5062:5062"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure
    container_name: dotnet-webapi-with-mysql
  db:
    image: "mysql:latest"
    environment:
      - "MYSQL_ROOT_PASSWORD=root"
      - "MYSQL_PASSWORD=root"
    container_name: mysql
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=root --execute \"SHOW DATABASES;\""
      interval: 2s
      timeout: 20s
      retries: 10
